### ISSUE TITLE
Setup Step 2 (on Mac)

### ISSUE THREAD

**Issue by Xinhao221b** [printyourbrain/PrintYourBrain#2]
For user in container

Error message: 
docker: Error response from daemon: Mounts denied: 
The path /Applications/freesurfer/7.2.0/license.txt is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.

Solution: 
add the path of freesurfer license to Docker -> Preferences -> Resources -> File Sharing.

**Comment by anujanegi** [comment]
Thank you for providing the solution! Ways to get docker to run on your system, are highly OS-dependent and hence a pre-requisite for PYB!
