### ISSUE TITLE
Processing brain scans Step 2 (on Mac)

### ISSUE THREAD

**Issue by Xinhao221b** [printyourbrain/PrintYourBrain#3]
python -m pip install --upgrade build

Warning message:
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by anujanegi** [comment]
As you are inside our custom docker when running this, it is completely fine :)
