### ISSUE TITLE
n00b questions: conda vs. container?

### ISSUE THREAD

**Issue by neurotransmitori** [printyourbrain/PrintYourBrain#4]
It may be helpful to describe under what conditions one would want to use a container vs. a conda environment

**Comment by anujanegi** [comment]
This depends highly on the person trying to use the package and their system.
A good way to decide according to me-
If your current system setup already fulfills 2/3 of the pre-requisites of going the conda environment way, then you probably are a neuroimaging ninja and should use the conda environment directly!
Else, docker to save time!
